# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uy7w4_lwIYhs17AxByxPgX1wRAfQsPIa
"""

import streamlit as st
import pandas as pd
import sqlite3
import os

# ページのタイトル設定（wideモードで横幅を最大化）
st.set_page_config(page_title="第十九改正日本薬局方 検索ツール", layout="wide")

# CSSで表の表示をさらにコンパクトにする設定
st.markdown("""
    <style>
    .main > div {
        padding-top: 2rem;
    }
    div[data-testid="stDataFrame"] > div {
        height: 800px; /* 表の表示高さを大きく固定 */
    }
    </style>
    """, unsafe_allow_html=True)

st.title("🧪 第十九改正日本薬局方 検索システム")

# データベース接続関数
def get_data(query, params=()):
    conn = sqlite3.connect('jp_pharmacopoeia.db')
    df = pd.read_sql(query, conn, params=params)
    conn.close()
    return df

# --- サイドバー ---
st.sidebar.header("表示フィルター")
category_filter = st.sidebar.multiselect(
    "カテゴリー選択",
    options=["化学薬品等", "生薬等"],
    default=["化学薬品等", "生薬等"]
)

st.sidebar.subheader("クイック検索")
only_new = st.sidebar.checkbox("✨ 新規収載のみ表示")
only_kaisei = st.sidebar.checkbox("📝 改正がある品目のみ表示")

# --- メイン画面 ---
search_query = st.text_input("医薬品名を入力してください", "")

# 抽出ロジック（中略：変更なし）
sql = "SELECT * FROM pharmaceuticals WHERE 1=1"
params = []
if search_query:
    sql += " AND 医薬品名 LIKE ?"
    params.append(f"%{search_query}%")
if only_new:
    sql += " AND 新規 = '〇'"
if only_kaisei:
    sql += " AND 改正 = '〇'"
if category_filter:
    sql += f" AND カテゴリー IN ({','.join(['?']*len(category_filter))})"
    params.extend(category_filter)

df_result = get_data(sql, params)

if not df_result.empty:
    st.success(f"{len(df_result)} 件ヒット（スクロールで全件確認できます）")

    display_cols = ['医薬品名', '頁', '新規', '改正', '変更項目', 'カテゴリー']
    actual_cols = [c for c in display_cols if c in df_result.columns]
    final_df = df_result[actual_cols]

    # スタイリング関数
    def color_o(val):
        if val == '〇':
            return 'background-color: #ffeb3b; color: black; font-weight: bold'
        return ''

    # バージョン互換性のあるスタイル適用
    try:
        styled_df = final_df.style.map(color_o, subset=['新規', '改正'])
    except AttributeError:
        styled_df = final_df.style.applymap(color_o, subset=['新規', '改正'])

    # --- 【改良点】表示設定を強化 ---
    st.dataframe(
        styled_df,
        use_container_width=True,
        hide_index=True,
        height=800, # ここで高さを大きく固定（約25-30行が一度に見えます）
        column_config={
            "医薬品名": st.column_config.TextColumn("医薬品名", width="large"),
            "変更項目": st.column_config.TextColumn("変更項目", width="medium"),
        }
    )

    csv = df_result.to_csv(index=False).encode('utf_8_sig')
    st.download_button(label="📥 結果をCSVで保存", data=csv, file_name="results.csv", mime='text/csv')
else:
    st.info("該当なし")