# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G6PeqwMQmMRQ0sQs7Ks_WjciAVYiDWtf
"""

import streamlit as st
import pandas as pd
import sqlite3
import os

# --- 設定項目 ---
DB_NAME = 'jp_pharmacopoeia.db'

# ページの基本設定
st.set_page_config(page_title="日本薬局方 検索システム", page_icon="📖", layout="wide")

# CSSによるレイアウト調整（効かないヘッダー用CSSを削除し軽量化）
st.markdown("""
    <style>
    /* 全体の余白とタイトルの見切れ防止 */
    .block-container {
        padding-top: 4.5rem !important;
        padding-bottom: 1rem !important;
        padding-left: 1.0rem !important;
        padding-right: 1.0rem !important;
    }
    .main-title {
        text-align: center;
        font-size: 1.6rem;
        font-weight: bold;
        margin-bottom: 25px;
        color: #1E3A8A;
        line-height: 1.2;
    }

    /* ボタンの間隔を限界まで詰める */
    [data-testid="column"] {
        padding: 0px !important;
        margin: 0px !important;
        flex: 1 1 0% !important;
        min-width: 0 !important;
    }
    [data-testid="stHorizontalBlock"] {
        gap: 0px !important;
    }

    /* ボタンのスタイル調整 */
    .stButton > button {
        width: 100% !important;
        border-radius: 0px !important;
        height: 2.4em !important;
        padding: 0px 2px !important;
        font-size: 0.75rem !important;
        background-color: #f8f9fa !important;
        border: 1px solid #ced4da !important;
        margin: 0px !important;
        white-space: nowrap !important;
        overflow: hidden !important;
    }
    [data-testid="column"]:not(:last-child) .stButton > button {
        border-right: none !important;
    }
    .stButton > button:hover {
        background-color: #e9ecef !important;
        border-color: #adb5bd !important;
        z-index: 1;
    }
    </style>
    <h1 class="main-title">第十九改正日本薬局方 新規収載・改正品検索システム</h1>
    """, unsafe_allow_html=True)

# --- データベース関連関数 ---
def get_db_connection():
    if os.path.exists(DB_NAME):
        return sqlite3.connect(DB_NAME)
    return None

def load_data():
    conn = get_db_connection()
    if conn:
        df = pd.read_sql("SELECT * FROM pharmaceuticals", conn)
        if '項番（行番号）' in df.columns:
            df = df.rename(columns={'項番（行番号）': '項番'})

        for col in df.columns:
            df[col] = df[col].fillna('').astype(str)
        conn.close()
        return df
    return pd.DataFrame()

def highlight_cells(val):
    if val == '〇':
        return 'background-color: #ffff00; color: black;'
    return ''

# データの読み込み
df_raw = load_data()

if df_raw.empty:
    st.error(f"❌ データベース `{DB_NAME}` が見つかりません。")
    st.stop()

if 'selected_kana' not in st.session_state:
    st.session_state.selected_kana = "全件表示"

# --- メイン画面上部: 検索エリア ---
search_word = st.text_input("🔍 検索", placeholder="品目名を入力してください", label_visibility="collapsed")

# カタカナボタン
kana_groups = {
    "ア行(ア～オ)": list("アイウエオ"), "カ行(カ～コ)": list("カキクケコ"), "サ行(サ～ソ)": list("サシスセソ"),
    "タ行(タ～ト)": list("タチツテト"), "ナ行(ナ～ノ)": list("ナニヌネノ"), "ハ行(ハ～ホ)": list("ハヒフヘホ"),
    "マ行(マ～モ)": list("マミムメモ"), "ヤ行(ヤ～ヨ)": list("ヤユヨ"), "ラ行(ラ～ロ)": list("ラリルレロ"),
    "ワ行(ワ)": list("ワ"), "全件表示": "全件表示"
}

cols = st.columns(len(kana_groups))
for i, label in enumerate(kana_groups.keys()):
    with cols[i]:
        if st.button(label):
            st.session_state.selected_kana = label

# --- サイドバー: フィルター設定 ---
st.sidebar.header("⚙️ フィルター設定")
selected_cats = [cat for cat in (df_raw['カテゴリー'].unique() if 'カテゴリー' in df_raw.columns else []) if st.sidebar.checkbox(cat, value=True)]
only_new = st.sidebar.checkbox("新規収載品のみ")
only_revised = st.sidebar.checkbox("改正品目のみ")

st.sidebar.subheader("行削除フィルタ")
remove_chem_row = st.sidebar.checkbox("「化学名」を含む行を削除")
remove_seijo_row = st.sidebar.checkbox("「4.生薬の性状」を含む行を削除")

# --- データフィルタリング ---
df_filtered = df_raw.copy()

if selected_cats: df_filtered = df_filtered[df_filtered['カテゴリー'].isin(selected_cats)]
if only_new: df_filtered = df_filtered[df_filtered['新規'] == '〇']
if only_revised: df_filtered = df_filtered[df_filtered['改正'] == '〇']

if search_word: df_filtered = df_filtered[df_filtered['医薬品名'].str.contains(search_word, na=False)]
sel_kana = st.session_state.selected_kana
if sel_kana != "全件表示":
    df_filtered = df_filtered[df_filtered['医薬品名'].str[0].isin(kana_groups[sel_kana])]

if '変更項目' in df_filtered.columns:
    if remove_chem_row:
        df_filtered = df_filtered[~((df_filtered['カテゴリー'] == '化学薬品等') & (df_filtered['変更項目'].str.contains('化学名', na=False)))]
    if remove_seijo_row:
        df_filtered = df_filtered[~((df_filtered['カテゴリー'] == '生薬等') & (df_filtered['変更項目'].str.contains('4.生薬の性状', na=False)))]

# --- 結果表示 ---
st.write(f"📊 検索結果: **{len(df_filtered)}** 件 / 選択中: {sel_kana}")

if not df_filtered.empty:
    display_cols = ['項番', '医薬品名', '頁', '新規', '改正', '変更項目', 'カテゴリー']
    final_cols = [c for c in display_cols if c in df_filtered.columns]

    styled_df = df_filtered[final_cols].style.map(
        highlight_cells, subset=['新規', '改正'] if '新規' in df_filtered.columns and '改正' in df_filtered.columns else []
    )

    st.dataframe(
        styled_df,
        use_container_width=True,
        hide_index=True,
        height=800,
        column_config={
            "項番": st.column_config.Column(width=60, alignment="right"),
            "医薬品名": st.column_config.Column(width=500, alignment="left"),
            "頁": st.column_config.Column(width=50, alignment="center"),
            "新規": st.column_config.Column(width=50, alignment="center"),
            "改正": st.column_config.Column(width=50, alignment="center"),
            "カテゴリー": st.column_config.Column(width=100, alignment="center"),
            "変更項目": st.column_config.Column(width="large"),
        }
    )
else:
    st.info("条件に一致する品目が見つかりませんでした。")